name: activity-action
description: An action that pulls repository activities.
author: Ao Li <aoli@andrew.cmu.edu>
branding:
  icon: activity
  color: orange
inputs:
  template:
    description: 'Input markdown template.'
  output:
    description: 'Output markdown path.'
  version:
    description: "Release version to use (default to latest)."
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Set reusable variables
      shell: bash
      run: |
        echo "action_repo=activity-action" >> $GITHUB_ENV
        echo "action_org=aoli-al" >> $GITHUB_ENV
        echo "binary_name=activity-action" >> $GITHUB_ENV

    - name: Download Action
      shell: bash
      run: |
        gh release download ${{ input.version }} --repo ${{ env.action_org }}/${{ env.action_repo }} --pattern '${{ runner.os }}.tgz'
        tar -xzf ${{ runner.os }}.tgz
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Run Action
      shell: bash
      id: run
      run: ./${{ runner.os }}/${{ env.binary_name }} "${{ inputs.template }}" "${{ inputs.output }}" "${{ github.repository }}"
